apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: rapidfort
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: kshitijagarwal24/rapidfort-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: http://api-gateway-service:5000/api
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: rapidfort
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
  selector:
    app: frontend
