apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: doc-uploads-pvc
  namespace: rapidfort
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: doc-output-pvc
  namespace: rapidfort
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
